### ISSUE TITLE
2.0.0 seems not to be published to npm 

### ISSUE THREAD

**Issue by kevohagan** [KevinGimbel/eleventy-plugin-mermaid#3]
I updated to 2.0.0 throuhg npm but it does not seem to take your latest changes. (latest publish was 8 months ago) 

https://www.npmjs.com/package/@kevingimbel/eleventy-plugin-mermaid?activeTab=readme 
documentation still references
 ```
<script async src="${src}">mermaid.initialize({ startOnLoad: true });</script>
```

**Comment by KevinGimbel** [comment]
Thanks!

I changed the README after I published the changes to NPM, that's why they didn't show up.

I now published v2.0.2 with the README changes and some more files added to the `.npmignore`. See https://github.com/KevinGimbel/eleventy-plugin-mermaid/commit/c037fb448cb3dcc32f4152f595722e7291f3c189 and https://github.com/KevinGimbel/eleventy-plugin-mermaid/commit/6fc577a6eb845eaf95dfed5d16fb6d2549a5939d

NPM now also shows the "last published" date as today, not sure why this wasn't picked up before 🤔
